USE DB;
GO
IF OBJECT_ID('dbo.RESULTS', 'U') IS NOT NULL DROP TABLE dbo.RESULTS;
IF OBJECT_ID('dbo.MATCH_TABLE', 'U') IS NOT NULL DROP TABLE dbo.MATCH_TABLE;
IF OBJECT_ID('dbo.SELECTED_MEMBER', 'U') IS NOT NULL DROP TABLE dbo.SELECTED_MEMBER;
IF OBJECT_ID('dbo.REQUEST', 'U') IS NOT NULL DROP TABLE dbo.REQUEST;
IF OBJECT_ID('dbo.INVITED_PARTICIPANTS', 'U') IS NOT NULL DROP TABLE dbo.INVITED_PARTICIPANTS;
IF OBJECT_ID('dbo.TOURNAMENT', 'U') IS NOT NULL DROP TABLE dbo.TOURNAMENT;
IF OBJECT_ID('dbo.ORGANAZER_TOUR', 'U') IS NOT NULL DROP TABLE dbo.ORGANAZER_TOUR;
IF OBJECT_ID('dbo.FIGHTER', 'U') IS NOT NULL DROP TABLE dbo.FIGHTER;
IF OBJECT_ID('dbo.CLUB', 'U') IS NOT NULL DROP TABLE dbo.CLUB;
IF OBJECT_ID('dbo.USER_PROFILE', 'U') IS NOT NULL DROP TABLE dbo.USER_PROFILE;
IF OBJECT_ID('dbo.DRAW', 'V') IS NOT NULL DROP VIEW dbo.DRAW;
GO


CREATE TABLE USER_PROFILE (
	USER_PROFILE_ID uniqueidentifier PRIMARY KEY DEFAULT NEWID(),
	USERNAME NVARCHAR(150) UNIQUE NOT NULL,
	PROFILE_TYPE INT NOT NULL,
	E_MAIL NVARCHAR(150) UNIQUE NOT NULL,
	PROFILE_PASSWORD NVARCHAR(100) NOT NULL,
);

CREATE TABLE CLUB (
	USER_PROFILE_ID uniqueidentifier NOT NULL,
    CLUB_ID uniqueidentifier PRIMARY KEY DEFAULT NEWID(),
    TITLE NVARCHAR(127) NOT NULL,
    DESCRIPTION_TEXT NVARCHAR(1000) NULL,
    FOUNDED_DATE DATE NOT NULL,
    CONTACT NVARCHAR(127) NULL,
    RATING FLOAT NOT NULL CHECK (RATING BETWEEN 0 AND 5),
    COUNTRY NVARCHAR(127) NOT NULL
	FOREIGN KEY (USER_PROFILE_ID) REFERENCES USER_PROFILE(USER_PROFILE_ID)
);

CREATE TABLE FIGHTER (
	USER_PROFILE_ID uniqueidentifier NOT NULL,
    FIGHTER_ID uniqueidentifier PRIMARY KEY DEFAULT NEWID(),
    NAME_TEXT NVARCHAR(127) NULL,
    BIRTHDAY DATE NOT NULL,
    DESCRIPTION_TEXT NVARCHAR(1000) NULL,
    CATEGORY INT NOT NULL CHECK (CATEGORY >= 0),
    RATING FLOAT NOT NULL CHECK (RATING BETWEEN 0 AND 5),
    COUNTRY NVARCHAR(127) NOT NULL,
    CLUB_ID uniqueidentifier,
    FOREIGN KEY (CLUB_ID) REFERENCES CLUB(CLUB_ID),
	FOREIGN KEY (USER_PROFILE_ID) REFERENCES USER_PROFILE(USER_PROFILE_ID)
);

CREATE TABLE ORGANAZER_TOUR (
	USER_PROFILE_ID uniqueidentifier NOT NULL,
    ORGANAZER_ID uniqueidentifier PRIMARY KEY DEFAULT NEWID(),
    TITLE NVARCHAR(100) NOT NULL,
    DESCRIPTION_TEXT NVARCHAR(1000) NULL,
    FOUNDATION_DATE DATE NOT NULL,
    ADDRESS_TEXT NVARCHAR(127) NOT NULL,
    CONTACT_INFO NVARCHAR(255) NULL,
	FOREIGN KEY (USER_PROFILE_ID) REFERENCES USER_PROFILE(USER_PROFILE_ID),
);

CREATE TABLE TOURNAMENT (
    TOURNAMENT_ID uniqueidentifier PRIMARY KEY DEFAULT NEWID(),
    TITLE NVARCHAR(100) NOT NULL,
    START_DATE DATE NOT NULL,
    END_DATE DATE NOT NULL,
	ADDRESS NVARCHAR(200) NOT NULL,
    ORGANAZER_ID uniqueidentifier NOT NULL,
    ROUNDS_NUMBER INT NOT NULL CHECK (ROUNDS_NUMBER > 0),
	CATEGORY INT NOT NULL,
    FOREIGN KEY (ORGANAZER_ID) REFERENCES ORGANAZER_TOUR(ORGANAZER_ID)
);

CREATE TABLE INVITED_PARTICIPANTS (
    FIGHTER_ID uniqueidentifier,
    TOURNAMENT_ID uniqueidentifier,
    INVITED_PARTICIPANTS_ID uniqueidentifier PRIMARY KEY DEFAULT NEWID(),
    FOREIGN KEY (FIGHTER_ID) REFERENCES FIGHTER(FIGHTER_ID),
    FOREIGN KEY (TOURNAMENT_ID) REFERENCES TOURNAMENT(TOURNAMENT_ID)
);

CREATE TABLE REQUEST (
    REQUEST_ID uniqueidentifier PRIMARY KEY DEFAULT NEWID(),
    FIGHTER_ID uniqueidentifier,
    TOURNAMENT_ID uniqueidentifier,
    INVITED_PARTICIPANTS_ID uniqueidentifier,
    DECISION INT NOT NULL CHECK (DECISION IN (0, 1)),
    FOREIGN KEY (FIGHTER_ID) REFERENCES FIGHTER(FIGHTER_ID),
    FOREIGN KEY (TOURNAMENT_ID) REFERENCES TOURNAMENT(TOURNAMENT_ID),
    FOREIGN KEY (INVITED_PARTICIPANTS_ID) REFERENCES INVITED_PARTICIPANTS(INVITED_PARTICIPANTS_ID)
);

CREATE TABLE SELECTED_MEMBER (
    PARTICIPANT_ID uniqueidentifier PRIMARY KEY DEFAULT NEWID(),
    REQUEST_ID uniqueidentifier NOT NULL,
    FIGHTER_ID uniqueidentifier NOT NULL, 
    TOURNAMENT_ID uniqueidentifier NOT NULL,
    FOREIGN KEY (FIGHTER_ID) REFERENCES FIGHTER(FIGHTER_ID),
    FOREIGN KEY (TOURNAMENT_ID) REFERENCES TOURNAMENT(TOURNAMENT_ID),
    FOREIGN KEY (REQUEST_ID) REFERENCES REQUEST(REQUEST_ID)
);

CREATE TABLE MATCH_TABLE (
    MATCH_ID uniqueidentifier PRIMARY KEY DEFAULT NEWID(),
    TOURNAMENT_ID uniqueidentifier,
    MATCH_NUMBER INT NOT NULL,
    ROUND_NUMBER INT NOT NULL CHECK (ROUND_NUMBER > 0),
    TOP_PARTICIPANT_ID uniqueidentifier NULL,
    BOTTOM_PARTICIPANT_ID uniqueidentifier NULL,
    WHEN_PLAYED DATE NULL,
    WINNER_ID uniqueidentifier NULL,
    TOP_SCORE INT NULL,
    BOTTOM_SCORE INT NULL,
    FOREIGN KEY (TOURNAMENT_ID) REFERENCES TOURNAMENT(TOURNAMENT_ID),
    FOREIGN KEY (TOP_PARTICIPANT_ID) REFERENCES SELECTED_MEMBER(PARTICIPANT_ID),
    FOREIGN KEY (BOTTOM_PARTICIPANT_ID) REFERENCES SELECTED_MEMBER(PARTICIPANT_ID),
    FOREIGN KEY (WINNER_ID) REFERENCES SELECTED_MEMBER(PARTICIPANT_ID)
);

CREATE TABLE RESULTS (
    TOURNAMENT_ID uniqueidentifier,
    ROUND_NUMBER INT NULL,
    MATCH_ID uniqueidentifier NOT NULL,
    PARTICIPANT_ID uniqueidentifier NOT NULL,
    PLACE INT NOT NULL CHECK (PLACE >= 1),
    FOREIGN KEY (TOURNAMENT_ID) REFERENCES TOURNAMENT(TOURNAMENT_ID),
    FOREIGN KEY (MATCH_ID) REFERENCES MATCH_TABLE(MATCH_ID),
    FOREIGN KEY (PARTICIPANT_ID) REFERENCES SELECTED_MEMBER(PARTICIPANT_ID)
);



GO
CREATE VIEW DRAW AS
SELECT 
    M.MATCH_ID,
    M.TOURNAMENT_ID,
    M.MATCH_NUMBER,
    M.ROUND_NUMBER,
    TM_TOP.FIGHTER_ID AS TOP_FIGHTER_NAME,
    TM_BOTTOM.FIGHTER_ID AS BOTTOM_FIGHTER_NAME,
    M.WHEN_PLAYED,
    M.WINNER_ID,
    M.TOP_SCORE,
    M.BOTTOM_SCORE
FROM 
    MATCH_TABLE M
LEFT JOIN 
    SELECTED_MEMBER TM_TOP ON M.TOP_PARTICIPANT_ID = TM_TOP.PARTICIPANT_ID
LEFT JOIN 
    SELECTED_MEMBER TM_BOTTOM ON M.BOTTOM_PARTICIPANT_ID = TM_BOTTOM.PARTICIPANT_ID WHERE M.ROUND_NUMBER = 1;
go
