USE DB;
GO
CREATE TRIGGER trg_InsertClub
ON CLUB
INSTEAD OF INSERT
AS
BEGIN
    IF EXISTS (SELECT 1 FROM CLUB WHERE TITLE IN (SELECT TITLE FROM INSERTED))
    BEGIN
        RAISERROR ('Клуб с таким названием уже существует', 16, 1);
        RETURN;
    END

    INSERT INTO CLUB (USER_PROFILE_ID, CLUB_ID, TITLE, DESCRIPTION_TEXT, FOUNDED_DATE, CONTACT, RATING, COUNTRY)
    SELECT USER_PROFILE_ID, CLUB_ID, TITLE, DESCRIPTION_TEXT, FOUNDED_DATE, CONTACT, RATING, COUNTRY
    FROM INSERTED;
END;
GO

CREATE TRIGGER trg_UpdateClub
ON CLUB
INSTEAD OF UPDATE
AS
BEGIN
    IF EXISTS (SELECT 1 FROM CLUB WHERE TITLE IN (SELECT TITLE FROM INSERTED) 
               AND CLUB_ID NOT IN (SELECT CLUB_ID FROM INSERTED))
    BEGIN
        RAISERROR ('Клуб с таким названием уже существует', 16, 1);
        RETURN;
    END

    UPDATE CLUB
    SET TITLE = i.TITLE,
        DESCRIPTION_TEXT = i.DESCRIPTION_TEXT,
        FOUNDED_DATE = i.FOUNDED_DATE,
        CONTACT = i.CONTACT,
        RATING = i.RATING,
        COUNTRY = i.COUNTRY,
        USER_PROFILE_ID = i.USER_PROFILE_ID
    FROM INSERTED i
    WHERE CLUB.CLUB_ID = i.CLUB_ID;
END;
GO


CREATE TRIGGER trg_DeleteClub
ON CLUB
INSTEAD OF DELETE
AS
BEGIN
    UPDATE FIGHTER
    SET CLUB_ID = NULL
    WHERE CLUB_ID IN (SELECT CLUB_ID FROM DELETED);

    DELETE FROM CLUB
    WHERE CLUB_ID IN (SELECT CLUB_ID FROM DELETED);
END;
GO

CREATE TRIGGER trg_InsertFighter
ON FIGHTER
INSTEAD OF INSERT
AS
BEGIN
    IF EXISTS (SELECT 1 FROM INSERTED WHERE BIRTHDAY IS NULL OR RATING IS NULL)
    BEGIN
        RAISERROR ('Не заполнены обязательные поля: BIRTHDAY, RATING', 16, 1);
        RETURN;
    END

    INSERT INTO FIGHTER (USER_PROFILE_ID, FIGHTER_ID, NAME_TEXT, BIRTHDAY, DESCRIPTION_TEXT, CATEGORY, RATING, COUNTRY, CLUB_ID)
    SELECT USER_PROFILE_ID, FIGHTER_ID, NAME_TEXT, BIRTHDAY, DESCRIPTION_TEXT, CATEGORY, RATING, COUNTRY, CLUB_ID 
    FROM INSERTED;
END;
GO

CREATE TRIGGER trg_UpdateFighter
ON FIGHTER
INSTEAD OF UPDATE
AS
BEGIN
    IF EXISTS (SELECT 1 FROM INSERTED WHERE BIRTHDAY IS NULL OR RATING IS NULL)
    BEGIN
        RAISERROR ('Не заполнены обязательные поля: BIRTHDAY, RATING', 16, 1);
        RETURN;
    END

    UPDATE FIGHTER
    SET USER_PROFILE_ID = i.USER_PROFILE_ID,
        NAME_TEXT = i.NAME_TEXT,
        BIRTHDAY = i.BIRTHDAY,
        DESCRIPTION_TEXT = i.DESCRIPTION_TEXT,
        CATEGORY = i.CATEGORY,
        RATING = i.RATING,
        COUNTRY = i.COUNTRY,
        CLUB_ID = i.CLUB_ID
    FROM INSERTED i
    WHERE FIGHTER.FIGHTER_ID = i.FIGHTER_ID;
END;
GO


CREATE TRIGGER trg_InsertTournament
ON TOURNAMENT
INSTEAD OF INSERT
AS
BEGIN
    IF EXISTS (SELECT 1 FROM TOURNAMENT WHERE TITLE IN (SELECT TITLE FROM INSERTED))
    BEGIN
        RAISERROR ('Турнир с таким названием уже существует', 16, 1);
    END
    ELSE IF EXISTS (SELECT 1 FROM INSERTED WHERE START_DATE > END_DATE)
    BEGIN
        RAISERROR ('Дата начала турнира не может быть позже даты окончания', 16, 1);
    END
    ELSE
    BEGIN
        INSERT INTO TOURNAMENT (TOURNAMENT_ID, TITLE, START_DATE, END_DATE, ORGANAZER_ID, ROUNDS_NUMBER, CATEGORY, ADDRESS)
        SELECT TOURNAMENT_ID, TITLE, START_DATE, END_DATE, ORGANAZER_ID, ROUNDS_NUMBER, CATEGORY, ADDRESS
        FROM INSERTED;
    END
END;
GO

CREATE TRIGGER trg_UpdateTournament
ON TOURNAMENT
INSTEAD OF UPDATE
AS
BEGIN
    IF EXISTS (SELECT 1 FROM TOURNAMENT WHERE TITLE IN (SELECT TITLE FROM INSERTED) AND TOURNAMENT_ID NOT IN (SELECT TOURNAMENT_ID FROM INSERTED))
    BEGIN
        RAISERROR ('Турнир с таким названием уже существует', 16, 1);
    END
    ELSE IF EXISTS (SELECT 1 FROM INSERTED WHERE START_DATE > END_DATE)
    BEGIN
        RAISERROR ('Дата начала турнира не может быть позже даты окончания', 16, 1);
    END
    ELSE
    BEGIN
        UPDATE TOURNAMENT
        SET TITLE = INSERTED.TITLE,
			ADDRESS = INSERTED.ADDRESS,
            START_DATE = INSERTED.START_DATE,
            END_DATE = INSERTED.END_DATE,
            ORGANAZER_ID = INSERTED.ORGANAZER_ID,
            ROUNDS_NUMBER = INSERTED.ROUNDS_NUMBER
        FROM INSERTED
        WHERE TOURNAMENT.TOURNAMENT_ID = INSERTED.TOURNAMENT_ID;
    END
END;
GO

CREATE TRIGGER trg_LimitTournamentParticipants
ON SELECTED_MEMBER
INSTEAD OF INSERT
AS
BEGIN
    DECLARE @tournamentID uniqueidentifier;
    DECLARE @maxParticipants INT;
    DECLARE @currentCount INT;

    SELECT @tournamentID = TOURNAMENT_ID FROM INSERTED;
	SELECT @maxParticipants = POWER(2, ROUNDS_NUMBER) FROM TOURNAMENT WHERE TOURNAMENT_ID = @tournamentID;
    SELECT @currentCount = COUNT(*) 
    FROM SELECTED_MEMBER 
    WHERE TOURNAMENT_ID = @tournamentID;

    DECLARE @requestID uniqueidentifier;
    DECLARE @fighterID uniqueidentifier;

    DECLARE cursor_selected CURSOR FOR
    SELECT REQUEST_ID, FIGHTER_ID FROM INSERTED;

    OPEN cursor_selected;
    FETCH NEXT FROM cursor_selected INTO @requestID, @fighterID;

    WHILE @@FETCH_STATUS = 0
    BEGIN
        IF (@currentCount < @maxParticipants)
        BEGIN
            INSERT INTO SELECTED_MEMBER (REQUEST_ID, FIGHTER_ID, TOURNAMENT_ID)
            VALUES (@requestID, @fighterID, @tournamentID);

            SET @currentCount = @currentCount + 1; 
        END
        ELSE
        BEGIN
            RAISERROR ('Невозможно добавить участника: максимальное количество участников достигнуто.', 16, 1);
            BREAK;
        END

        FETCH NEXT FROM cursor_selected INTO @requestID, @fighterID;
    END

    CLOSE cursor_selected;
    DEALLOCATE cursor_selected;
END;
GO

CREATE TRIGGER trg_InsertRequest
ON REQUEST
INSTEAD OF INSERT
AS
BEGIN
    DECLARE @fighterID uniqueidentifier;
    DECLARE @tournamentID uniqueidentifier;
    DECLARE @invitedParticipantsID uniqueidentifier;

    SELECT @fighterID = FIGHTER_ID, 
           @tournamentID = TOURNAMENT_ID 
    FROM INSERTED;

    IF @fighterID <> '00000000-0000-0000-0000-000000000000'
    BEGIN
        IF EXISTS (
            SELECT 1 
            FROM REQUEST 
            WHERE FIGHTER_ID = @fighterID 
              AND TOURNAMENT_ID = @tournamentID
        )
        BEGIN
            RAISERROR ('Невозможно добавить заявку: боец уже зарегистрирован на этот турнир.', 16, 1);
            RETURN;
        END
    

    SELECT @invitedParticipantsID = INVITED_PARTICIPANTS_ID 
    FROM INVITED_PARTICIPANTS 
    WHERE FIGHTER_ID = @fighterID AND TOURNAMENT_ID = @tournamentID;

    IF @invitedParticipantsID IS NOT NULL
    BEGIN
        INSERT INTO REQUEST (REQUEST_ID, FIGHTER_ID, TOURNAMENT_ID, INVITED_PARTICIPANTS_ID, DECISION)
        SELECT REQUEST_ID, FIGHTER_ID, TOURNAMENT_ID, @invitedParticipantsID, 1  -- Положительное решение
        FROM INSERTED;
    END
    ELSE
    BEGIN
        INSERT INTO REQUEST (REQUEST_ID, FIGHTER_ID, TOURNAMENT_ID, DECISION)
        SELECT REQUEST_ID, FIGHTER_ID, TOURNAMENT_ID, 0  -- Негативное решение
        FROM INSERTED;
    END
	END
END
GO

CREATE TRIGGER trg_PreventDuplicateMatchNumbers
ON MATCH_TABLE
INSTEAD OF INSERT
AS
BEGIN
    DECLARE @tournamentID uniqueidentifier;
    DECLARE @matchNumber INT;

    SELECT 
        @tournamentID = TOURNAMENT_ID, 
        @matchNumber = MATCH_NUMBER 
    FROM INSERTED;

    IF EXISTS (
        SELECT 1 
        FROM MATCH_TABLE 
        WHERE TOURNAMENT_ID = @tournamentID 
          AND MATCH_NUMBER = @matchNumber
    )
    BEGIN
        RAISERROR ('Невозможно добавить матч: матч с таким номером уже существует для данного турнира.', 16, 1);
        RETURN; 
    END

    INSERT INTO MATCH_TABLE (TOURNAMENT_ID, MATCH_NUMBER, ROUND_NUMBER, TOP_PARTICIPANT_ID, BOTTOM_PARTICIPANT_ID, WHEN_PLAYED, WINNER_ID, TOP_SCORE, BOTTOM_SCORE)
    SELECT  
        TOURNAMENT_ID, 
        MATCH_NUMBER, 
        ROUND_NUMBER, 
        TOP_PARTICIPANT_ID, 
        BOTTOM_PARTICIPANT_ID, 
        WHEN_PLAYED, 
        WINNER_ID, 
        TOP_SCORE, 
        BOTTOM_SCORE 
    FROM INSERTED;
END;
GO


CREATE TRIGGER trg_AfterDelete_Fighter
ON FIGHTER
INSTEAD OF DELETE
AS
BEGIN
    DECLARE @DeletedFighterID UNIQUEIDENTIFIER;
    DECLARE @DefaultFighterID UNIQUEIDENTIFIER = '00000000-0000-0000-0000-000000000000';  -- Замените на фактический ID

    SELECT @DeletedFighterID = FIGHTER_ID FROM DELETED;

    IF NOT EXISTS (SELECT 1 FROM SELECTED_MEMBER WHERE FIGHTER_ID = @DeletedFighterID)
    BEGIN
        DELETE FROM REQUEST
        WHERE REQUEST_ID IN (
            SELECT r.REQUEST_ID
            FROM REQUEST r
            LEFT JOIN SELECTED_MEMBER sm ON r.REQUEST_ID = sm.REQUEST_ID
            GROUP BY r.REQUEST_ID
            HAVING COUNT(sm.PARTICIPANT_ID) = 0
        );

        DELETE FROM INVITED_PARTICIPANTS
        WHERE FIGHTER_ID = @DeletedFighterID;
    END
    ELSE
    BEGIN
        UPDATE REQUEST
        SET FIGHTER_ID = @DefaultFighterID
        WHERE FIGHTER_ID = @DeletedFighterID;

        UPDATE INVITED_PARTICIPANTS
        SET FIGHTER_ID = @DefaultFighterID
        WHERE FIGHTER_ID = @DeletedFighterID;

        UPDATE SELECTED_MEMBER
        SET FIGHTER_ID = @DefaultFighterID
        WHERE FIGHTER_ID = @DeletedFighterID;
    END 

    DELETE FROM FIGHTER
    WHERE FIGHTER_ID = @DeletedFighterID;
END;
GO

CREATE TRIGGER trg_DeleteOrganizer
ON ORGANAZER_TOUR
INSTEAD OF DELETE
AS
BEGIN
    DECLARE @OldOrganazerId uniqueidentifier;

    SELECT @OldOrganazerId = ORGANAZER_ID FROM DELETED;

    DECLARE @NewOrganazerId uniqueidentifier = '00000000-0000-0000-0000-000000000000'; -- Укажите заранее известный id организатора
    UPDATE TOURNAMENT
    SET ORGANAZER_ID = @NewOrganazerId
    WHERE ORGANAZER_ID = @OldOrganazerId;

    DELETE FROM ORGANAZER_TOUR
    WHERE ORGANAZER_ID = @OldOrganazerId;
END;
GO

CREATE TRIGGER trg_UpdateOrganizerTour
ON ORGANAZER_TOUR
INSTEAD OF UPDATE
AS
BEGIN
    IF EXISTS (SELECT 1 FROM ORGANAZER_TOUR WHERE TITLE IN (SELECT TITLE FROM INSERTED) 
               AND ORGANAZER_ID NOT IN (SELECT ORGANAZER_ID FROM INSERTED))
    BEGIN
        RAISERROR ('Организатор с таким названием уже существует', 16, 1);
        RETURN;
    END

    UPDATE ORGANAZER_TOUR
    SET TITLE = i.TITLE,
        DESCRIPTION_TEXT = i.DESCRIPTION_TEXT,
        FOUNDATION_DATE = i.FOUNDATION_DATE,
        ADDRESS_TEXT = i.ADDRESS_TEXT,
        CONTACT_INFO = i.CONTACT_INFO,
        USER_PROFILE_ID = i.USER_PROFILE_ID
    FROM INSERTED i
    WHERE ORGANAZER_TOUR.ORGANAZER_ID = i.ORGANAZER_ID;
END;
GO

CREATE TRIGGER trg_InsertOrganizerTour
ON ORGANAZER_TOUR
INSTEAD OF INSERT
AS
BEGIN
    IF EXISTS (SELECT 1 FROM ORGANAZER_TOUR WHERE TITLE IN (SELECT TITLE FROM INSERTED))
    BEGIN
        RAISERROR ('Организатор с таким названием уже существует', 16, 1);
        RETURN;
    END

    INSERT INTO ORGANAZER_TOUR (USER_PROFILE_ID, ORGANAZER_ID, TITLE, DESCRIPTION_TEXT, FOUNDATION_DATE, ADDRESS_TEXT, CONTACT_INFO)
    SELECT USER_PROFILE_ID, ORGANAZER_ID, TITLE, DESCRIPTION_TEXT, FOUNDATION_DATE, ADDRESS_TEXT, CONTACT_INFO
    FROM INSERTED;
END;
GO

CREATE TRIGGER trg_update_decision_on_delete_invited_participants
ON INVITED_PARTICIPANTS
INSTEAD OF DELETE
AS
BEGIN
    UPDATE REQUEST
    SET DECISION = 0
    WHERE INVITED_PARTICIPANTS_ID IN (SELECT INVITED_PARTICIPANTS_ID FROM DELETED);

    DELETE FROM INVITED_PARTICIPANTS
    WHERE INVITED_PARTICIPANTS_ID IN (SELECT INVITED_PARTICIPANTS_ID FROM DELETED);
END;
GO

CREATE TRIGGER trg_prevent_duplicate_invitation
ON INVITED_PARTICIPANTS
INSTEAD OF INSERT
AS
BEGIN
    IF EXISTS (
        SELECT 1
        FROM INVITED_PARTICIPANTS AS ip
        JOIN inserted AS i
        ON ip.FIGHTER_ID = i.FIGHTER_ID 
        AND ip.TOURNAMENT_ID = i.TOURNAMENT_ID
    )
    BEGIN
        RAISERROR('Приглашение уже существует для данного бойца на этот турнир.', 16, 1);
        ROLLBACK TRANSACTION; 
        RETURN;
    END

    INSERT INTO INVITED_PARTICIPANTS (FIGHTER_ID, TOURNAMENT_ID)
    SELECT FIGHTER_ID, TOURNAMENT_ID
    FROM inserted;
END;
GO


CREATE TRIGGER DeleteTournamentCascade
ON TOURNAMENT
INSTEAD OF DELETE
AS
BEGIN

	DELETE FROM RESULTS
    WHERE TOURNAMENT_ID IN (SELECT TOURNAMENT_ID FROM DELETED);

    DELETE FROM MATCH_TABLE
    WHERE TOURNAMENT_ID IN (SELECT TOURNAMENT_ID FROM DELETED);    
    
    DELETE FROM SELECTED_MEMBER
    WHERE TOURNAMENT_ID IN (SELECT TOURNAMENT_ID FROM DELETED);
    
    DELETE FROM REQUEST
    WHERE TOURNAMENT_ID IN (SELECT TOURNAMENT_ID FROM DELETED);
    
    DELETE FROM INVITED_PARTICIPANTS
    WHERE TOURNAMENT_ID IN (SELECT TOURNAMENT_ID FROM DELETED);
    
    DELETE FROM TOURNAMENT
    WHERE TOURNAMENT_ID IN (SELECT TOURNAMENT_ID FROM DELETED);
END;
GO

CREATE TRIGGER trg_prevent_delete_request
ON REQUEST
INSTEAD OF DELETE
AS
BEGIN
    DECLARE @fighter_id uniqueidentifier;

    DECLARE delete_cursor CURSOR FOR
    SELECT FIGHTER_ID
    FROM DELETED;

    OPEN delete_cursor;
    FETCH NEXT FROM delete_cursor INTO @fighter_id;

    WHILE @@FETCH_STATUS = 0
    BEGIN
        IF EXISTS (SELECT 1 FROM SELECTED_MEMBER WHERE FIGHTER_ID = @fighter_id)
        BEGIN
            RAISERROR('Удаление записи запрещено, так как боец связан с выбранным участником.', 16, 1);
            CLOSE delete_cursor;
            DEALLOCATE delete_cursor;
            RETURN;
        END

        FETCH NEXT FROM delete_cursor INTO @fighter_id;
    END

    CLOSE delete_cursor;
    DEALLOCATE delete_cursor;

    DELETE FROM REQUEST
    WHERE REQUEST_ID IN (SELECT REQUEST_ID FROM DELETED);
END;
GO

CREATE TRIGGER trg_InsertUserProfile
ON USER_PROFILE
INSTEAD OF INSERT
AS
BEGIN
    IF EXISTS (SELECT 1 FROM USER_PROFILE WHERE USERNAME IN (SELECT USERNAME FROM INSERTED))
    BEGIN
        RAISERROR('Ошибка: Имя пользователя должно быть уникальным.', 16, 1);
        RETURN;
    END

    IF EXISTS (SELECT 1 FROM USER_PROFILE WHERE E_MAIL IN (SELECT E_MAIL FROM INSERTED))
    BEGIN
        RAISERROR('Ошибка: Адрес электронной почты должен быть уникальным.', 16, 1);
        RETURN;
    END

    INSERT INTO USER_PROFILE (USER_PROFILE_ID, USERNAME, PROFILE_TYPE, E_MAIL, PROFILE_PASSWORD)
    SELECT USER_PROFILE_ID, USERNAME, PROFILE_TYPE, E_MAIL, PROFILE_PASSWORD
    FROM INSERTED;
END;
GO

CREATE TRIGGER trg_DeleteUserProfile
ON USER_PROFILE
INSTEAD OF DELETE
AS
BEGIN
    IF EXISTS (SELECT 1 FROM CLUB WHERE USER_PROFILE_ID IN (SELECT USER_PROFILE_ID FROM DELETED)) OR 
       EXISTS (SELECT 1 FROM FIGHTER WHERE USER_PROFILE_ID IN (SELECT USER_PROFILE_ID FROM DELETED)) OR 
       EXISTS (SELECT 1 FROM ORGANAZER_TOUR WHERE USER_PROFILE_ID IN (SELECT USER_PROFILE_ID FROM DELETED))
    BEGIN
        RAISERROR('Удаление невозможно, связанная запись существует в одной из связанных таблиц.', 16, 1);
        RETURN;
    END

    DELETE FROM USER_PROFILE
    WHERE USER_PROFILE_ID IN (SELECT USER_PROFILE_ID FROM DELETED);
END;
GO

CREATE TRIGGER trg_UpdateUserProfile
ON USER_PROFILE
INSTEAD OF UPDATE
AS
BEGIN
    IF EXISTS (SELECT 1 FROM USER_PROFILE WHERE USERNAME IN (SELECT USERNAME FROM INSERTED) 
               AND USER_PROFILE_ID NOT IN (SELECT USER_PROFILE_ID FROM INSERTED))
    BEGIN
        RAISERROR('Ошибка: Имя пользователя должно быть уникальным.', 16, 1);
        RETURN;
    END

    IF EXISTS (SELECT 1 FROM USER_PROFILE WHERE E_MAIL IN (SELECT E_MAIL FROM INSERTED) 
               AND USER_PROFILE_ID NOT IN (SELECT USER_PROFILE_ID FROM INSERTED))
    BEGIN
        RAISERROR('Ошибка: Адрес электронной почты должен быть уникальным.', 16, 1);
        RETURN;
    END

    UPDATE USER_PROFILE
    SET USERNAME = i.USERNAME,
        PROFILE_TYPE = i.PROFILE_TYPE,
        E_MAIL = i.E_MAIL,
        PROFILE_PASSWORD = i.PROFILE_PASSWORD
    FROM INSERTED i
    WHERE USER_PROFILE.USER_PROFILE_ID = i.USER_PROFILE_ID;
END;
GO
